name: flutter_stft_fft_plugin
description: KissFFT-based native FFT/STFT plugin for Flutter (Dart FFI).
version: 0.0.1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.0

dev_dependencies:
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
